package com.company.controller;

public enum CommandName {
    CREATE_USERPROFILE_COMMAND,
    CHOOSE_USERPROFILE_COMMAND,
    SHOW_USERPROFILE_COMMAND,
    UPDATE_USERPROFILE_COMMAND,
    DELETE_USERPROFILE_COMMAND,
    SEARCHBYNAME_USERPROFILE_COMMAND,
    SEARCHBYSURNAME_USERPROFILE_COMMAND,
    SORTBYNAME_USERPROFILE_COMMAND,
    SORTBYAGE_USERPROFILE_COMMAND,
    SORTBYCREATIONDATE_USERPROFILE_COMMAND,
    CREATE_USERORDER_COMMAND,
    SHOW_USERORDER_COMMAND,
    UPDATE_USERORDER_COMMAND,
    DELETE_USERORDER_COMMAND,
    SORTBYCOFFEEAMOUNT_USERORDER_COMMAND,
    SORTBYDATE_USERORDER_COMMAND,
    SORTBYID_USERORDER_COMMAND,
    EXIT_COMMAND,
    NO_SUCH_COMMAND
}
